package Evanaciam;

import com.sun.media.jfxmedia.events.PlayerStateEvent;
import com.sun.org.glassfish.external.statistics.Stats;

import java.util.HashMap;
import java.util.Hashtable;

/**
 * Created by qrsu on 3/02/2016.
 */
public class storyLog {
// This is a class that will access story milestones generated by player interaction and parse the events back into a story log, converting from
// first to third person.


//Method to use when milestones are reached. Pass several variables into it to generate unique identifier
  public void storeLog(){
  }
}
